title: My Life Rules!
author: Nicholas Nasr
email: nick.nasr@emory.edu
description: > # this means to ignore newlines until "baseurl:"
  This site is a test site as I navigate github.

# social links
twitter_username: n/a
github_username:  nnasr

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
